#!/usr/bin/env python3
from scapy.all import *
import socket

while True:
	packet = sr1(IP(dst='128.119.243.134')/UDP(dport=5300)/DNS(rd=0,qd=DNSQR(qname='falun.com')), verbose=0,timeout=5)


	print(packet.summary())
