#!/usr/bin/env python3
import scapy.all as scapy
import socket

answer = sr1(IP(dst='172.30.192.1')/UDP(dport=53)/DNS(rd=1,qd=DNSQR(qname='www.thepacketgeek.com')), verbose=0)


print(answer.summar())
