#!/usr/bin/env python3
from scapy.all import *
import socket
import time


start = time.time()
packet = IP(dst='128.119.243.134')/UDP(dport=5300)
ans,unans = sr(packet/DNS(rd=1,qd=DNSQR(qname='falun.com')), multi=10,verbose=0,timeout = 5)
end = time.time()-start
print(ans[0])
print(ans[1])
